In [2]:
import pandas as pd

In [49]:
attendance_df = pd.read_csv('data.csv', usecols=[0, 1, 2, 3, 4], header=None)
attendance_df = attendance_df.rename(columns={0:'Monday', 1:'Tuesday', 2:'Wednesday', 3:'Thursday', 4: 'Friday'})
attendance_df.head()

    Monday  Tuesday Wednesday Thursday   Friday
0  8:56 AM  9:00 AM   7:45 AM  7:45 AM  8:05 AM
1  8:40 AM  8:40 AM   8:30 AM  8:30 AM  8:45 AM
2  8:45 AM  8:20 AM   8:05 AM  8:00 AM  8:05 AM
3  8:40 AM  8:40 AM   8:40 AM  8:25 AM  8:40 AM
4  8:55 AM  8:50 AM   8:55 AM  8:10 AM  8:15 AM

In [50]:
attendance_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23 entries, 0 to 22
Data columns (total 5 columns):
Monday       23 non-null object
Tuesday      23 non-null object
Wednesday    23 non-null object
Thursday     23 non-null object
Friday       23 non-null object
dtypes: object(5)
memory usage: 1000.0+ bytes

In [51]:
attendance_df

     Monday   Tuesday Wednesday Thursday   Friday
0   8:56 AM   9:00 AM   7:45 AM  7:45 AM  8:05 AM
1   8:40 AM   8:40 AM   8:30 AM  8:30 AM  8:45 AM
2   8:45 AM   8:20 AM   8:05 AM  8:00 AM  8:05 AM
3   8:40 AM   8:40 AM   8:40 AM  8:25 AM  8:40 AM
4   8:55 AM   8:50 AM   8:55 AM  8:10 AM  8:15 AM
5   8:45 AM   8:45 AM   8:45 AM  8:40 AM  8:30 AM
6   8:45 AM   8:54 AM   8:38 AM  8:40 AM  8:32 AM
7    absent  11:00 AM   8:35 AM  8:15 AM  8:10 AM
8   8:39 AM   8:13 AM   8:15 AM  8:12 AM  8:10 AM
9   9:00 AM   8:50 AM   8:50 AM  8:50 AM  8:40 AM
10  8:40 AM   8:50 AM   8:40 AM  8:34 AM  8:20 AM
11  8:15 AM   8:30 AM   8:13 AM  8:30 AM  7:45 AM
12  8:45 AM   8:55 AM   8:45 AM  8:45 AM  8:00 AM
13  8:45 AM   8:45 AM   8:05 AM  8:00 AM  8:00 AM
14  8:45 AM   8:45 AM   9:00 AM  9:00 AM  8:50 AM
15  8:15 AM   8:40 AM   8:25 AM  8:30 AM  7:30 AM
16  8:45 AM   8:40 AM   8:45 AM  8:55 AM  8:45 AM
17  8:45 AM   9:00 AM   9:00 AM  9:00 AM  9:00 AM
18  8:50 AM   8:50 AM   8:57 AM  8:42 AM  8:35 AM
19  8:15 AM   9:00 AM   8:35 AM  9:00 AM  8:58 AM
20  8:45 AM   8:35 AM   8:27 AM  8:46 AM  8:31 AM
21  8:45 AM   8:45 AM   9:00 AM  8:57 AM  8:57 AM
22  8:45 AM   8:50 AM   8:30 AM  8:45 AM  8:50 AM

There is no missing data, however there is an absence on Monday.

In [55]:
attendance_df = attendance_df.pd.Timestamp()
attendance_df.info()

AttributeError: 'DataFrame' object has no attribute 'pd'